<?php
/**
 * Faq Categories List
 *
 * @var $block \Infobeans\Faq\Block\Sidebar\Category
 */
?>
<?php $items = $this->getCategories(); ?>

<?php if (count($items)) {  
    
    ?>

<div class="faq-category"> 
    
	<ul>
	<?php
		$i = 0;		 
		foreach($items as $item) { 
                    if($i==0)
                    {
                        $currentCategory=$item->getId(); 
                    }
                    
                    ?>
			 
            <li id="cat<?php echo $item->getId();?>" <?php echo ($i == 0)?'class="active"':''?> >
                        <a  href="javascript:;" <?php echo ($i == 0)?'class="disableClick"':''?> onclick="fetchFaq('<?php echo $item->getId();?>',1)">
			    <?php echo $block->escapeHtml($item->getCategoryName()) ?>
			</a>
	        <?php
		$i++;	 
		}
   	?>
	</ul>
</div>
<input type="hidden" id="current-category" value="<?php echo $currentCategory;?>" />
<?php } ?>
<script type="text/javascript">
    window.accordianEnable=parseInt("<?php echo $this->isEnableAccordian(); ?>");
    window.faqAjaxUrl="<?php echo $this->getBaseUrl(); ?>faq/ajax/index";
</script>    